# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-30 12:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessLoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('end_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('repayment', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('reference', models.CharField(max_length=12)),
                ('phone', models.IntegerField(unique=True)),
                ('status', models.CharField(choices=[('rent', 'Rent'), ('with_mortgage', 'Own with Mortgage'), ('without_mortgage', 'Own without Mortgage'), ('none', "Don't pay rent or Mortgage")], default='rent', max_length=30)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
            ],
        ),
    ]
