# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-28 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans_app', '0002_auto_20170728_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessLoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=20)),
                ('phone', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=125)),
                ('region', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('rent', 'Rent'), ('with_mortgage', 'Own with Mortgage'), ('without_mortgage', 'Own without Mortgage'), ('none', "Don't pay rent or Mortgage")], default='rent', max_length=30)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans_app.UserProfile')),
            ],
        ),
    ]
